security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: lazy
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: logout
                target: home
    access_control:
        - { path: ^/orders, roles: ROLE_USER }
        - { path: ^/order/*, roles: ROLE_USER }
        - { path: ^/address/add, roles: ROLE_USER }
        - { path: ^/address/select, roles: ROLE_USER }
        - { path: ^/checkout, roles: ROLE_USER }