version: "3.8"
networks:
  lamp:
    name: lamp
    driver: bridge
services:
  apache:
    container_name: apache
    image: rthompson961/apache
    networks:
      - lamp
    ports:
      - "80:80"
    volumes:
      - $PWD:/var/www/html
    environment:
      - DB_URL=mysql://root:root@mysql:3306/clothes?serverVersion=5.7
    depends_on:
      - mysql
  mysql:
    container_name: mysql
    image: "mysql:5.7"
    networks:
      - lamp
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root